version: '3.9'
services:
  app:
    container_name: app
    build: ./
    ports:
      - "3001:3001"
    platform: linux/x86_64
    working_dir: /app
    command: npm run dev
    volumes:
      - ./src:/app/src
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/event_manager
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsoft", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
  db:
    image: 'postgres:latest'
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_manager
    restart: 'always'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d event_manager -U user" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
